### ISSUE TITLE
what is format of quotaObject in updateUserQuota and updateBucketQuota methods ?

### ISSUE THREAD

**Issue by leohihimax** [tobilg/ceph-admin-ops-client#1]
Hi, what is the format of  quotaObject in updateUserQuota and updateBucketQuota methods?

like
```
{
  "max_buckets": 100,
  "max_size": 4096
}
```
or something else?

Thank you

**Comment by tobilg** [comment]
See http://docs.ceph.com/docs/master/radosgw/adminops/#set-user-quota

> The content must include a JSON representation of the quota settings as encoded in the corresponding read operation.
